/*
 * Do not edit this file directly! It is generated from
 * `tools/entity_types.cpp` by the build system at compile time.
 */

#include "../math/types.h"

#include "entity_types.h"

i32 format(char *buffer, u32 size, FormatHint args, EntityType type) {
    switch (type) {
        case EntityType::BASEENTITY: return snprintf(buffer, size, "BaseEntity");
        case EntityType::ENTITY: return snprintf(buffer, size, "Entity");
        case EntityType::PLAYER: return snprintf(buffer, size, "Player");
        case EntityType::SOUNDENTITY: return snprintf(buffer, size, "SoundEntity");
        case EntityType::TESTENT: return snprintf(buffer, size, "TestEnt");
        default: UNREACHABLE("Unknown entity type");
    }
    return 0;
}

/*
 * Included from `tools/entity_types_type_of.cpp`
 */

EntityType type_of(BaseEntity *e) {
    return EntityType::BASEENTITY;
}

EntityType type_of(Entity *e) {
    return EntityType::ENTITY;
}

EntityType type_of(Player *e) {
    return EntityType::PLAYER;
}

EntityType type_of(SoundEntity *e) {
    return EntityType::SOUNDENTITY;
}

EntityType type_of(TestEnt *e) {
    return EntityType::TESTENT;
}


/*
 * End of `tools/entity_types_type_of.cpp`
 */
