/*
 * Do not edit this file directly! It is generated from
 * `tools/entity_types.h` by the build system at compile time.
 */

#pragma once

#include "../util/util.h"

enum class EntityType {
$types

    NUM_ENTITY_TYPES,
};

i32 format(char *, u32, FormatHint, EntityType);

/*
 * Included from `tools/entity_types_type_of.h`
 */

$type_ofs

/*
 * End of `tools/entity_types_type_of.h`
 */
