/*
 * Do not edit this file directly! It is generated from
 * `tools/entity_types_template.h` by the build system at compile time.
 */

enum EntityType {
$types

    NUM_ENTITY_TYPES,
};

bool is_same_type(BaseEntity a, BaseEntity b) {
    return a.metadata.type == b.metadata.type;
}
