name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syy
          pacman --noconfirm -S binutils gcc clang python python-pip python-wheel sdl2 scons git glibc
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: requirements.txt
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          source venv/bin/activate
          scons -Q tests --ci --report --jumbo
      - name: Upload build
        if: ${{ !success() }}
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            bin/tests/SMEK
            bin/tests/assets*.bin
      - name: Upload report
        if: ${{ !success() }}
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: |
            bin/tests/report.txt
      - name: Try to build release version (g++)
        run: |
          source venv/bin/activate
          scons -Q --release --no-imgui --jumbo CXX=g++
      - name: Try to build release version (clang++)
        run: |
          source venv/bin/activate
          scons -Q --release --no-imgui --jumbo CXX=clang++
